stages:
  - build
  # - test

build:
  stage: build
  image: node
  script:
    - yarn
    - yarn lint
    - yarn build
    - echo "BUILD SUCCESSFUL"
# test:
#   stage: test
#   image: node
#   script:
#     - yarn
#     - yarn test
#     - echo "TEST SUCCESSFUL"
