name: Publish - Stable
on:
  workflow_dispatch:
jobs:
  release-linux:
    name: Release - Linux
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn
      - name: Package - Linux
        run: yarn package
      - uses: actions/upload-artifact@v2
        with:
          name: releases-linux
          path: release/*.snap

  release-windows:
    name: Release - Windows
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn
      - name: Package - Windows
        run: yarn package
      - uses: actions/upload-artifact@v2
        with:
          name: releases-windows
          path: release\*.exe

  publish-linux:
    name: Publish - Linux
    needs:
      - release-linux
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: mkdir release
      - uses: actions/download-artifact@v2
        with:
          name: releases-linux
          path: release/
      - name: Install Tool - Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        with:
          snapcraft_token: ${{ secrets.SNAPCRAFT_TOKEN_STABLE }}
      - name: Get Application Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Publish Snap
        run: snapcraft upload --release stable release/noetter_${{ steps.package-version.outputs.current-version}}_amd64.snap

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs:
      - release-linux
      - publish-linux
      - release-windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: mkdir release
      - uses: actions/download-artifact@v2
        with:
          name: releases-linux
          path: release/
      - uses: actions/download-artifact@v2
        with:
          name: releases-windows
          path: release/
      - name: Get Application Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.package-version.outputs.current-version}}+${{ github.run_number }}
          draft: false
          prerelease: false
          files: |
            release/*.snap
            release/*.exe
          body: |
            Download one of the artifacts below or install it on your linux distribution using snap `snap install noetter`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
