# This is a basic workflow to help you get started with Actions

name: Publish - Edge

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
      - feature/release-artifacts

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release-linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Tool - Node
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: Install Dependencies
        run: |
          npm install -g yarn
          yarn

      - name: Package - Linux
        run: yarn package-linux

      - uses: actions/upload-artifact@v2
        with:
          name: releases-linux
          path: |
            release/*.snap

  release-windows:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Tool - Node
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: Install Dependencies
        run: |
          npm install -g yarn
          yarn --network-timeout 100000

      - name: Package - Windows
        run: yarn package-win

      - uses: actions/upload-artifact@v2
        with:
          name: releases-windows
          path: |
            release\*.exe

  publish:
    needs:
      - release-linux
    runs-on: ubuntu-20.04
    steps:
      - name: Install Tool - Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        with:
          snapcraft_token: ${{ secrets.SNAPCRAFT_TOKEN_EDGE }}

      - name: Get Application Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Publish Snap
        run: snapcraft upload --release edge release/noetter_${{ steps.package-version.outputs.current-version}}_amd64.snap
