name: Release - Test

on:
  push:
    branches:
      - feature/release-artifacts

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: mkdir release
      - uses: actions/download-artifact@v2
        with:
          name: releases-linux
          path: release/
      - uses: actions/download-artifact@v2
        with:
          name: releases-windows
          path: release/
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: edge/${{ github.run_number }}
          draft: true
          prerelease: true
          body: |
            This is an automatic bleeding edge release for the current master branch state.

            Download one of the artifacts below or install it on your linux distribution using snap `snap install noetter --edge`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
